---
- include: pyenv-dependencies-install-{{ ansible_distribution | lower }}.yml

- name: Pyenv - clone from github
  become: yes
  become_user: "{{ pyenv_user }}"
  git: repo=git://github.com/yyuu/pyenv.git dest="{{ pyenv_home }}"

- name: Pyenv - clone pyenv-virtualenv plugin from github
  become: yes
  become_user: "{{ pyenv_user }}"
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest="{{ pyenv_home }}/plugins/pyenv-virtualenv"
